### ISSUE TITLE
Logo Proposal for Gitmails

### ISSUE THREAD

**Issue by area55git** [giovanifss/Gitmails#1]
Hello, I wish to cooperate with **gitmails**, for this reason I have decided to design a logo for it. If you like this proposal, I can send you the files.

You can suggest the changes you think are necessary.

[![LOGO_PROPOSAL_FOR_GITMAILS.jpg](https://s9.postimg.cc/ftgzb2kpr/LOGO_PROPOSAL_FOR_GITMAILS.jpg)](https://postimg.cc/image/f3y6ypk63/)

**Comment by giovanifss** [comment]
Hello @area55git, thanks for the contact and suggestion. Just a quick questino: are you making a portfolio?

**Comment by area55git** [comment]
I'm only working in my area of work (graphic design), I'm new to github. If you like my proposal, I can send you the logo in several formats.

**Comment by giovanifss** [comment]
@area55git Ok, I really liked, it would be definitely a great addition. I just want to make sure you have a proper credit for this. Let`s do the following:
- Upload the files in any cloud service that you fell comfortable;
- Make sure that the first image have a public fixed link;
- Open a pull request adding it to the README;
- Add any link that can help you in the commit commentaries (like portfolio, pinterest, etc);
In this way you will be the author of the relevant commits to the logo and have a proper link to your work.

**Comment by area55git** [comment]
As I mentioned earlier, I am new to github and do not make an pull request, I will try it.

**Comment by giovanifss** [comment]
@area55git Its simple, I can help you with that.

- First you will need to fork the repository, by clicking here: https://github.com/giovanifss/Gitmails/fork
- Then you will go to your repository, will probably be: https://github.com/area55git/Gitmails
- Click in the README file and edit it, adding the link to the logo that you've made;
- Commit the file
- Come back here and open a new pull request by clicking here: https://github.com/giovanifss/Gitmails/compare

**Comment by area55git** [comment]
What proposal would you like?

[![LOGO_PROPOSAL_FOR_GITMAILS_2.jpg](https://s9.postimg.cc/mtdvcm2sv/LOGO_PROPOSAL_FOR_GITMAILS_2.jpg)](https://postimg.cc/image/3oam2uo4r/)

**Comment by giovanifss** [comment]
The second one, I really enjoy dark stuffs.

**Comment by area55git** [comment]
Perfect, today I will be sending the link to download the files.

**Comment by giovanifss** [comment]
@area55git Great! Thank you.

**Comment by area55git** [comment]
Remember, if you need a logo design you just have to make the request in my github account, I will gladly help you.

**Comment by area55git** [comment]
Hello @giovanifss, this is the link for downloading the logos. Enjoy them

# **[DOWNLOAD](https://drive.google.com/open?id=10IoAqyYKtUq7I_vYWk-sO5WSgNSnzZMp)**

[![licencia_OPENMF.jpg](https://s9.postimg.cc/m3vjjlgm7/licencia_OPENMF.jpg)](https://postimg.cc/image/xg851dpaz/)
This work is licensed under a Creative Commons Attribution 4.0 International License.

**Comment by giovanifss** [comment]
@area55git You are almost there. Just need to open a pull request with your fork ([right here](https://github.com/giovanifss/Gitmails/compare)) and then clicking in **compare across forks** and selecting your fork, [like in this tutorial](https://help.github.com/articles/creating-a-pull-request-from-a-fork/).

**Comment by area55git** [comment]
PR #4. I think I did it well.

**Comment by giovanifss** [comment]
@area55git Yeah, you did great. Thanks for the contribution!

**Comment by giovanifss** [comment]
@area55git could you update the logo? There was a typo in the text as reported in #5

**Comment by area55git** [comment]
ok

**Comment by area55git** [comment]
Here is corrected, I must make a new PR?

https://github.com/area55git/Gitmails/blob/master/README.md

**Comment by giovanifss** [comment]
Thanks. I will create it, its ok.
