### ISSUE TITLE
Undefined name 'repo_url' in core/utils/git.py

### ISSUE THREAD

**Issue by cclauss** [giovanifss/Gitmails#3]
https://github.com/giovanifss/Gitmails/blob/master/core/utils/git.py#L52

Should this be __repo.url__ instead of __repo_url__?

flake8 testing of https://github.com/giovanifss/Gitmails on Python 3.6.3

$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./core/utils/git.py:52:60: F821 undefined name 'repo_url'
                Helpers.print_success("Clonning {}".format(repo_url))
                                                           ^
1     F821 undefined name 'repo_url'
1
```

**Comment by giovanifss** [comment]
Yeah, it should. Great catch, thank you. Also, there was a mistake in the string format in https://github.com/giovanifss/Gitmails/blob/master/core/utils/git.py#L38, there was no mask for `repo_path`.
